- platform: mqtt
  state_topic: "HA/doors/entrydoor"
  name: "Entry Door"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "HA/window/diningroomwindow"
  name: "Dining Room Window"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "HA/motion/denmotion"
  name: "Den Motion"
  device_class: motion
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "HA/doors/reargaragedoor"
  name: "Rear Garage Door"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "HA/motion/masterbedroommotion"
  name: "Bedroom Motion"
  device_class: motion
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "HA/window/frontbedroomwindow"
  name: "Front Bedroom Window"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "HA/window/masterbedroomwindowr"
  name: "Bedroom Window Right"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "HA/window/masterbedroomwindowl"
  name: "Bedroom Window Left"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "HA/window/officewindow"
  name: "Office Window"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "HA/window/masterbathroomwindow"
  name: "Bathroom Window"
  device_class: opening
  payload_on: "1"
  payload_off: "0"



